[package]
name = "rust-web-boilerplate"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
tide = "0.1.1"
futures-preview = "0.3.0-alpha.14"
structopt = "0.2.15"

[dev-dependencies]
http-service-mock = "0.1.1"
http-service = "0.1.5"
